export { default as ChakraUiIcon } from './chakra-ui.svg'
export { default as ReactIcon } from './react.svg'
export { default as TypescriptIcon } from './typescript.svg'
export { default as ViteJsIcon } from './vitejs.svg'
export { default as FsdIcon } from './feature-sliced-design.png'
export { default as I18nIcon } from './i18next-icon.svg'
